 
##variable<-read.csv("dataoa.csv", header=TRUE, sep=",")

##lm1<-lm(variable$RP24 ~ variable$RP1 + variable$RP2)
##lmboth

##lm1 <- lm(variable$RP24 ~ variable$RP1)
##plot(variable$RP24,variable$RP1,pch=19,col="blue")
##lines(variable$RP1,lm1$fitted,lwd=3,col="darkgrey")

##MODELO LINEAL RP4 VS RP1 Y RECTAS 
##CON ESTO PLOTEO MI RESULTADO DE RP24 VS LAS OTRAS RP, COMO EJEMPLO SOLO TENGO RP1.
##Y LO HAGO PARA DOS DE LAS 3 MATERIAS DE OA
##EL RESULTADO FUE UNA GRAFICA CON DOS RECTAS CRUZAS. DIFERENTES PENDIENTES Y SPREAD DE DATOS DIFERENTES.

##lmSIS <- lm(variable$RP24[variable$MATERIA=="SIST. DE INFORMACION (CC)"] ~ variable$RP1[variable$MATERIA=="SIST. DE INFORMACION (CC)"])
##lmT <- lm(variable$RP24[variable$MATERIA=="SIST. TOMA DECISIONES"] ~ variable$RP1[variable$MATERIA=="SIST. TOMA DECISIONES"])
##plot(variable$RP1,variable$RP24,pch=19)
##points(variable$RP1,variable$RP24,pch=19,col=((variable$MATERIA=="SIST. DE INFORMACION (CC)")*1+1))
##lines(variable$RP1[variable$MATERIA=="SIST. DE INFORMACION (CC)"],lmSIS$fitted,col="black",lwd=3)
##lines(variable$RP1[variable$MATERIA=="SIST. TOMA DECISIONES"],lmT$fitted,col="red",lwd=3)
##FIN DE MODELO LINEAL 

##GENERACION DE REGLAS, PERO USANDO TODAS LAS VARIABLES SIN ELIMINAR LAS DE LA REGRESION
library(arules)
library(arulesViz)
library(RColorBrewer)
library(labdsv)
library(devtools)
install_github("ggbiplot", "vqv")
#librreria contiene scatterplotMatrix()
library(car)

getwd()
setwd("C:/Users/Otilia/My Documents/MIT R")
list.files()
dateDownloaded <- date()

##Esta parte es para que coja el archivo del profesor, lo ordene, lo convierta a matriz y finalmente imprima el heatmap

variable<-read.csv("encuestaoa2.csv", header=TRUE, sep=",")
scatterplotMatrix(variable[1:6])
plot(variable$X4, variable$X5, xlab='evaluat fit the topics in class', ylab='provide clear instructions', pch=8, cex=2, col='gray50', xlim=c(0,12), ylim=c(0,12))
text(variable$X4, variable$X5, variable$X24, cex=0.7, pos=4, col="red")
variable2<-variable[variable$X24=="E",]
sapply(variable2[1:23], mean)

standarvalues<- as.data.frame(scale(variable[1:23]))
variable.pca<-prcomp(standarvalues)
variable.pca$sdev
screeplot(variable.pca, type="lines")
(variable.pca$sdev)^2
variable.pca$rotation[,1]
sum((variable.pca$rotation[,1])^2)

printMeanAndSdByGroup <- function(variables,groupvariable)
{
  # find the names of the variables
  variablenames <- c(names(groupvariable),names(as.data.frame(variables)))
  # within each group, find the mean of each variable
  groupvariable <- groupvariable[,1] # ensures groupvariable is not a list
  means <- aggregate(as.matrix(variables) ~ groupvariable, FUN = mean)
  names(means) <- variablenames
  print(paste("Means:"))
  print(means)
  # within each group, find the standard deviation of each variable:
  sds <- aggregate(as.matrix(variables) ~ groupvariable, FUN = sd)
  names(sds) <- variablenames
  print(paste("Standard deviations:"))
  print(sds)
  # within each group, find the number of samples:
  samplesizes <- aggregate(as.matrix(variables) ~ groupvariable, FUN = length)
  names(samplesizes) <- variablenames
  print(paste("Sample sizes:"))
  print(samplesizes)
}


#PCA
#log transform
log.cv <- log(variable[, 1:23])

#apply PCA - scale. = TRUE is highly
#advisable, but default is FALSE

cv.pca<- prcomp(log.cv, center = TRUE, SCALE=TRUE)

#print method
print(cv.pca)

#plot method
plot(cv.pca)

#summary method
summary(cv.pca)

#para ver la parte roja
biplot(cv.pca, expand=1, xlim=c(-0.10,0.06), ylim=c(-0.05,0.05), cex = rep(par("cex"), 2))
#para ver la parte negra
biplot(cv.pca, expand=1, xlim=c(-0.08,-0.11), ylim=c(-0.02,0.04), cex = rep(par("cex"), 2))

#pagina para ver como se usa el biblot
#http://stackoverflow.com/questions/17055291/r-how-to-make-pca-biplot-more-readable
#http://www.r-bloggers.com/computing-and-visualizing-pca-in-r/
#http://little-book-of-r-for-multivariate-analysis.readthedocs.org/en/latest/src/multivariateanalysis.html
#http://www.meetup.com/PyLadiesMTL/events/209425182/?fromEmail=209425182&rv=md1


variable
##variable <- variable[order(variable$X1D_AUDIOVISUAL_HELP),]
variable_matrix <- data.matrix(variable)
variable_heatmap <- heatmap(variable_matrix, Rowv=NA, Colv=NA, col = heat.colors(256), scale="column", margins=c(5,10), cexRow=0.5, cexCol=0.5)
variable[["RP24"]]<-NULL

variable[[ "X1D_AUDIOVISUAL_HELP"]] <- ordered(cut(variable[[ "X1D_AUDIOVISUAL_HELP"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X2D_PRES_SCHED"]] <- ordered(cut(variable[[ "X2D_PRES_SCHED"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X3D_EVAL_PERIOD"]] <- ordered(cut(variable[[ "X3D_EVAL_PERIOD"]], c(4,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X4D_EVAL_RELAT_TOPICS"]] <- ordered(cut(variable[[ "X4D_EVAL_RELAT_TOPICS"]], c(0,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X5D_INSTR_FOR_ASSESSMENTS"]] <- ordered(cut(variable[[ "X5D_INSTR_FOR_ASSESSMENTS"]], c(4,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X6D_RESEARC_MOTIV"]] <- ordered(cut(variable[[ "X6D_RESEARC_MOTIV"]], c(0,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X7LP_PRE_INF_SCHED"]] <- ordered(cut(variable[[ "X7LP_PRE_INF_SCHED"]], c(2,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X8LP_PRE_INF_POLICY_CLASS"]] <- ordered(cut(variable[[ "X8LP_PRE_INF_POLICY_CLASS"]], c(1,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X9LP_ENCOUR_PARTICIP"]] <- ordered(cut(variable[[ "X9LP_ENCOUR_PARTICIP"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X10LP_SUMM_LAST_TOPICS"]] <- ordered(cut(variable[[ "X10LP_SUMM_LAST_TOPICS"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X11LP_NEWCONCEP_USING_LAST_KNOWLED"]] <- ordered(cut(variable[[ "X11LP_NEWCONCEP_USING_LAST_KNOWLED"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X12LP_MOTIV_LEARN_COURS_MATERIAL"]] <- ordered(cut(variable[[ "X12LP_MOTIV_LEARN_COURS_MATERIAL"]], c(0,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X13LP_ANSW_QUEST_OUTS_CLASS"]] <- ordered(cut(variable[[ "X13LP_ANSW_QUEST_OUTS_CLASS"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X14LP_REFLX_ON_TOPICS"]] <- ordered(cut(variable[[ "X14LP_REFLX_ON_TOPICS"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X15LP_COMMUNICATION"]] <- ordered(cut(variable[[ "X15LP_COMMUNICATION"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X16LP_RESPECTFUL"]] <- ordered(cut(variable[[ "X16LP_RESPECTFUL"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X17LP_ANSW_QUEST_OF_TOPICS"]] <- ordered(cut(variable[[ "X17LP_ANSW_QUEST_OF_TOPICS"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X18LP_CONTENT_ORGANIZ"]] <- ordered(cut(variable[[ "X18LP_CONTENT_ORGANIZ"]], c(0,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X19LP_CONT_UNDERST"]] <- ordered(cut(variable[[ "X19LP_CONT_UNDERST"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X20PT_PREPAR_RESOURCES"]] <- ordered(cut(variable[[ "X20PT_PREPAR_RESOURCES"]], c(2,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X21PT_USE_SCHEMES"]] <- ordered(cut(variable[[ "X21PT_USE_SCHEMES"]], c(0,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X22EM_RESULT_ASSES_ONTIME"]] <- ordered(cut(variable[[ "X22EM_RESULT_ASSES_ONTIME"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X23EM_ARRIVE_ONTIME"]]       <- ordered(cut(variable[[ "X23EM_ARRIVE_ONTIME"]], c(3,6,8,10)),labels = c("Regular", "Good", "Excellent"))
variable[[ "X24"]]       <- ordered(cut(variable[[ "X24"]], c(3,6,8,10)),labels = c("R", "G", "E"))

variable
str(variable)

variable_final<-as(variable,"transactions")
variable_final
variable_final[1:5,]
summary(variable_final)
itemFrequencyPlot(variable_final, support = 0.01, cex.names=0.5)

sort(variable$X1D_AUDIOVISUAL_HELP, decreasing=TRUE)
sort(variable$X2D_PRES_SCHED, decreasing=TRUE)
sort(variable$X3D_EVAL_PERIOD,decreasing=TRUE)
sort(variable$X4D_EVAL_RELAT_TOPICS, decreasing=TRUE)
sort(variable$X5D_INSTR_FOR_ASSESSMENTS, decreasing=TRUE)
sort(variable$X6D_RESEARC_MOTIV, decreasing=TRUE)
sort(variable$X7LP_PRE_INF_SCHED, decreasing=TRUE)
sort(variable$X8LP_PRE_INF_POLICY_CLASS, decreasing=TRUE)
sort(variable$X9LP_ENCOUR_PARTICIP, decreasing=TRUE)
sort(variable$X10LP_SUMM_LAST_TOPICS, decreasing=TRUE)
sort(variable$X11LP_NEWCONCEP_USING_LAST_KNOWLED, decreasing=TRUE)
sort(variable$X12LP_MOTIV_LEARN_COURS_MATERIAL, decreasing=TRUE)
sort(variable$X13LP_ANSW_QUEST_OUTS_CLASS, decreasing=TRUE)
sort(variable$X14LP_REFLX_ON_TOPICS, decreasing=TRUE)
sort(variable$X15LP_COMMUNICATION, decreasing=TRUE)
sort(variable$X16LP_RESPECTFUL, decreasing=TRUE)
sort(variable$X17LP_ANSW_QUEST_OF_TOPICS, decreasing=TRUE)
sort(variable$X18LP_CONTENT_ORGANIZ, decreasing=TRUE)
sort(variable$X19LP_CONT_UNDERST, decreasing=TRUE)
sort(variable$X20PT_PREPAR_RESOURCES, decreasing=TRUE)
sort(variable$X21PT_USE_SCHEMES, decreasing=TRUE)
sort(variable$X22EM_RESULT_ASSES_ONTIME, decreasing=TRUE)
sort(variable$X23EM_ARRIVE_ONTIME, decreasing=TRUE)
sort(variable$X24, decreasing=TRUE)

# EXCELLENT we need to see for excellent evaluations so we use a specific support , somtimes higher
# plot this to see what is in the rhs
# make an inspection about what we found in the rhs 

##sink("excellentresultsgce.txt")

rules<-apriori(variable_final,parameter=list(support=0.8,confidence=1))
saveAsGraph(head(sort(rules, by="lift"),50), file="CV32_08.graphml")

## Pares de atributos que generan unicamente combinacioin de variables objetivos


rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E9<-subset(rules12_15, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G9<-subset(rules12_15, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf12_15R9<-subset(rules12_15, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E9)
summary(rules_izquierda_plf12_15G9)
summary(rules_izquierda_plf12_15R9)
inspect(rules_izquierda_plf12_15E9)
inspect(rules_izquierda_plf12_15G9)
inspect(rules_izquierda_plf12_15R9)

rules12_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf12_19E9<-subset(rules12_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf12_19G9<-subset(rules12_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf12_19R9<-subset(rules12_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_19E9)
summary(rules_izquierda_plf12_19G9)
summary(rules_izquierda_plf12_19R9)
inspect(rules_izquierda_plf12_19E9)
inspect(rules_izquierda_plf12_19G9)
inspect(rules_izquierda_plf12_19R9)

rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E9<-subset(rules12_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G9<-subset(rules12_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf12_22R9<-subset(rules12_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E9)
summary(rules_izquierda_plf12_22G9)
summary(rules_izquierda_plf12_22R9)
inspect(rules_izquierda_plf12_22E9)
inspect(rules_izquierda_plf12_22G9)
inspect(rules_izquierda_plf12_22R9)

rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E9<-subset(rules15_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G9<-subset(rules15_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf15_19R9<-subset(rules15_19, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E9)
summary(rules_izquierda_plf15_19G9)
summary(rules_izquierda_plf15_19R9)
inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf15_19R9)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E9<-subset(rules15_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G9<-subset(rules15_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf15_22R9<-subset(rules15_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E9)
summary(rules_izquierda_plf15_22G9)
summary(rules_izquierda_plf15_22R9)
inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf15_19R9)

rules19_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X19LP_CONT_UNDERST=Excellent","X19LP_CONT_UNDERST=Good","X19LP_CONT_UNDERST=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf19_22E9<-subset(rules19_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
rules_izquierda_plf19_22G9<-subset(rules19_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
rules_izquierda_plf19_22R9<-subset(rules19_22, subset= rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.9)
summary(rules_izquierda_plf19_22E9)
summary(rules_izquierda_plf19_22G9)
summary(rules_izquierda_plf19_22R9)
inspect(rules_izquierda_plf19_22E9)
inspect(rules_izquierda_plf19_22G9)
inspect(rules_izquierda_plf19_22R9)

rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E19<-subset(rules12_15, subset= rhs %in% "X19LP_CONT_UNDERST=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G19<-subset(rules12_15, subset= rhs %in% "X19LP_CONT_UNDERST=Good" & lift > 0.9)
rules_izquierda_plf12_15R19<-subset(rules12_15, subset= rhs %in% "X19LP_CONT_UNDERST=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E19)
summary(rules_izquierda_plf12_15G19)
summary(rules_izquierda_plf12_15R19)
inspect(rules_izquierda_plf12_15E19)
inspect(rules_izquierda_plf12_15G19)
inspect(rules_izquierda_plf12_15R19)

rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E19<-subset(rules12_22, subset= rhs %in% "X19LP_CONT_UNDERST=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G19<-subset(rules12_22, subset= rhs %in% "X19LP_CONT_UNDERST=Good" & lift > 0.9)
rules_izquierda_plf12_22R19<-subset(rules12_22, subset= rhs %in% "X19LP_CONT_UNDERST=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E19)
summary(rules_izquierda_plf12_22G19)
summary(rules_izquierda_plf12_22R19)
inspect(rules_izquierda_plf12_22E19)
inspect(rules_izquierda_plf12_22G19)
inspect(rules_izquierda_plf12_22R19)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E19<-subset(rules15_22, subset= rhs %in% "X19LP_CONT_UNDERST=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G19<-subset(rules15_22, subset= rhs %in% "X19LP_CONT_UNDERST=Good" & lift > 0.9)
rules_izquierda_plf15_22R19<-subset(rules15_22, subset= rhs %in% "X19LP_CONT_UNDERST=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E19)
summary(rules_izquierda_plf15_22G19)
summary(rules_izquierda_plf15_22R19)
inspect(rules_izquierda_plf15_22E19)
inspect(rules_izquierda_plf15_22G19)
inspect(rules_izquierda_plf15_22R19)

rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E14<-subset(rules12_15, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G14<-subset(rules12_15, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf12_15R14<-subset(rules12_15, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E14)
summary(rules_izquierda_plf12_15G14)
summary(rules_izquierda_plf12_15R14)
inspect(rules_izquierda_plf12_15E14)
inspect(rules_izquierda_plf12_15G14)
inspect(rules_izquierda_plf12_15R14)

rules12_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf12_19E14<-subset(rules12_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf12_19G14<-subset(rules12_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf12_19R14<-subset(rules12_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_19E14)
summary(rules_izquierda_plf12_19G14)
summary(rules_izquierda_plf12_19R14)
inspect(rules_izquierda_plf12_19E14)
inspect(rules_izquierda_plf12_19G14)
inspect(rules_izquierda_plf12_19R14)


rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E14<-subset(rules12_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G14<-subset(rules12_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf12_22R14<-subset(rules12_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E14)
summary(rules_izquierda_plf12_22G14)
summary(rules_izquierda_plf12_22R14)
inspect(rules_izquierda_plf12_22E14)
inspect(rules_izquierda_plf12_22G14)
inspect(rules_izquierda_plf12_22R14)

rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E14<-subset(rules15_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G14<-subset(rules15_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf15_19R14<-subset(rules15_19, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E14)
summary(rules_izquierda_plf15_19G14)
summary(rules_izquierda_plf15_19R14)
inspect(rules_izquierda_plf15_19E14)
inspect(rules_izquierda_plf15_19G14)
inspect(rules_izquierda_plf15_19R14)

rules19_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X19LP_CONT_UNDERST=Excellent","X19LP_CONT_UNDERST=Good","X19LP_CONT_UNDERST=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf19_22E14<-subset(rules19_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf19_22G14<-subset(rules19_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf19_22R14<-subset(rules19_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf19_22E14)
summary(rules_izquierda_plf19_22G14)
summary(rules_izquierda_plf19_22R14)
inspect(rules_izquierda_plf19_22E14)
inspect(rules_izquierda_plf19_22G14)
inspect(rules_izquierda_plf19_22R14)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E14<-subset(rules15_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G14<-subset(rules15_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
rules_izquierda_plf15_22R14<-subset(rules15_22, subset= rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E14)
summary(rules_izquierda_plf15_22G14)
summary(rules_izquierda_plf15_22R14)
inspect(rules_izquierda_plf15_22E14)
inspect(rules_izquierda_plf15_22G14)
inspect(rules_izquierda_plf15_22R14)

rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E21<-subset(rules12_15, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G21<-subset(rules12_15, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf12_15R21<-subset(rules12_15, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E21)
summary(rules_izquierda_plf12_15G21)
summary(rules_izquierda_plf12_15R21)
inspect(rules_izquierda_plf12_15E21)
inspect(rules_izquierda_plf12_15G21)
inspect(rules_izquierda_plf12_15R21)

rules12_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf12_19E21<-subset(rules12_19, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf12_19G21<-subset(rules12_19, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf12_19R21<-subset(rules12_19, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_19E21)
summary(rules_izquierda_plf12_19G21)
summary(rules_izquierda_plf12_19R21)
inspect(rules_izquierda_plf12_19E21)
inspect(rules_izquierda_plf12_19G21)
inspect(rules_izquierda_plf12_19R21)

rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E6<-subset(rules12_15, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G6<-subset(rules12_15, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf12_15R6<-subset(rules12_15, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E6)
summary(rules_izquierda_plf12_15G6)
summary(rules_izquierda_plf12_15R6)
inspect(rules_izquierda_plf12_15E6)
inspect(rules_izquierda_plf12_15G6)
inspect(rules_izquierda_plf12_15R6)

rules12_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf12_19E6<-subset(rules12_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf12_19G6<-subset(rules12_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf12_19R6<-subset(rules12_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_19E6)
summary(rules_izquierda_plf12_19G6)
summary(rules_izquierda_plf12_19R6)
inspect(rules_izquierda_plf12_19E6)
inspect(rules_izquierda_plf12_19G6)
inspect(rules_izquierda_plf12_19R6)

rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E6<-subset(rules12_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G6<-subset(rules12_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf12_22R6<-subset(rules12_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E6)
summary(rules_izquierda_plf12_22G6)
summary(rules_izquierda_plf12_22R6)
inspect(rules_izquierda_plf12_22E6)
inspect(rules_izquierda_plf12_22G6)
inspect(rules_izquierda_plf12_22R6)

rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E6<-subset(rules15_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G6<-subset(rules15_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf15_19R6<-subset(rules15_19, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E6)
summary(rules_izquierda_plf15_19G6)
summary(rules_izquierda_plf15_19R6)
inspect(rules_izquierda_plf15_19E6)
inspect(rules_izquierda_plf15_19G6)
inspect(rules_izquierda_plf15_19R6)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E6<-subset(rules15_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G6<-subset(rules15_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf15_22R6<-subset(rules15_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E6)
summary(rules_izquierda_plf15_22G6)
summary(rules_izquierda_plf15_22R6)
inspect(rules_izquierda_plf15_22E6)
inspect(rules_izquierda_plf15_22G6)
inspect(rules_izquierda_plf15_22R6)

rules19_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X19LP_CONT_UNDERST=Excellent","X19LP_CONT_UNDERST=Good","X19LP_CONT_UNDERST=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf19_22E6<-subset(rules19_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
rules_izquierda_plf19_22G6<-subset(rules19_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
rules_izquierda_plf19_22R6<-subset(rules19_22, subset= rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.9)
summary(rules_izquierda_plf19_22E6)
summary(rules_izquierda_plf19_22G6)
summary(rules_izquierda_plf19_22R6)
inspect(rules_izquierda_plf19_22E6)
inspect(rules_izquierda_plf19_22G6)
inspect(rules_izquierda_plf19_22R6)

rules12_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf12_19E18<-subset(rules12_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf12_19G18<-subset(rules12_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf12_19R18<-subset(rules12_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_19E18)
summary(rules_izquierda_plf12_19G18)
summary(rules_izquierda_plf12_19R18)
inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf12_19R18)

rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E18<-subset(rules12_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G18<-subset(rules12_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf12_22R18<-subset(rules12_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E18)
summary(rules_izquierda_plf12_22G18)
summary(rules_izquierda_plf12_22R18)
inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf12_19R18)


rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E18<-subset(rules15_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G18<-subset(rules15_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf15_19R18<-subset(rules15_19, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E18)
summary(rules_izquierda_plf15_19G18)
summary(rules_izquierda_plf15_19R18)
inspect(rules_izquierda_plf15_19E18)
inspect(rules_izquierda_plf15_19G18)
inspect(rules_izquierda_plf15_19R18)

rules12_15<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X15LP_COMMUNICATION=Excellent", "X15LP_COMMUNICATION=Good", "X15LP_COMMUNICATION=Regular"), default="rhs"))
rules_izquierda_plf12_15E18<-subset(rules12_15, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf12_15G18<-subset(rules12_15, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf12_15R18<-subset(rules12_15, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_15E18)
summary(rules_izquierda_plf12_15G18)
summary(rules_izquierda_plf12_15R18)
inspect(rules_izquierda_plf12_15E18)
inspect(rules_izquierda_plf12_15G18)
inspect(rules_izquierda_plf12_15R18)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E18<-subset(rules15_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G18<-subset(rules15_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf15_22R18<-subset(rules15_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E18)
summary(rules_izquierda_plf15_22G18)
summary(rules_izquierda_plf15_22R18)
inspect(rules_izquierda_plf15_22E18)
inspect(rules_izquierda_plf15_22G18)
inspect(rules_izquierda_plf15_22R18)

rules19_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X19LP_CONT_UNDERST=Excellent","X19LP_CONT_UNDERST=Good","X19LP_CONT_UNDERST=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf19_22E18<-subset(rules19_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
rules_izquierda_plf19_22G18<-subset(rules19_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
rules_izquierda_plf19_22R18<-subset(rules19_22, subset= rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda_plf19_22E18)
summary(rules_izquierda_plf19_22G18)
summary(rules_izquierda_plf19_22R18)
inspect(rules_izquierda_plf19_22E18)
inspect(rules_izquierda_plf19_22G18)
inspect(rules_izquierda_plf19_22R18)

rules12_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent","X12LP_MOTIV_LEARN_COURS_MATERIAL=Good","X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf12_22E21<-subset(rules12_22, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf12_22G21<-subset(rules12_22, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf12_22R21<-subset(rules12_22, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf12_22E21)
summary(rules_izquierda_plf12_22G21)
summary(rules_izquierda_plf12_22R21)
inspect(rules_izquierda_plf12_22E21)
inspect(rules_izquierda_plf12_22G21)
inspect(rules_izquierda_plf12_22R21)


rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E21<-subset(rules15_19, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G21<-subset(rules15_19, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf15_19R21<-subset(rules15_19, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E21)
summary(rules_izquierda_plf15_19G21)
summary(rules_izquierda_plf15_19R21)
inspect(rules_izquierda_plf15_19E21)
inspect(rules_izquierda_plf15_19G21)
inspect(rules_izquierda_plf15_19R21)

rules19_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X19LP_CONT_UNDERST=Excellent","X19LP_CONT_UNDERST=Good","X19LP_CONT_UNDERST=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf19_22E21<-subset(rules19_22, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf19_22G21<-subset(rules19_22, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf19_22R21<-subset(rules19_22, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf19_22E21)
summary(rules_izquierda_plf19_22G21)
summary(rules_izquierda_plf19_22R21)
inspect(rules_izquierda_plf19_22E21)
inspect(rules_izquierda_plf19_22G21)
inspect(rules_izquierda_plf19_22R21)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E21<-subset(rules15_22, subset= rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G21<-subset(rules15_22, subset= rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
rules_izquierda_plf15_22R21<-subset(rules15_22, subset= rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E21)
summary(rules_izquierda_plf15_22G21)
summary(rules_izquierda_plf15_22R21)
inspect(rules_izquierda_plf15_22E21)
inspect(rules_izquierda_plf15_22G21)
inspect(rules_izquierda_plf15_22R21)


rules15_19<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X19LP_CONT_UNDERST=Excellent", "X19LP_CONT_UNDERST=Good", "X19LP_CONT_UNDERST=Regular"), default="rhs"))
rules_izquierda_plf15_19E12<-subset(rules15_19, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent" & lift > 0.9)
rules_izquierda_plf15_19G12<-subset(rules15_19, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Good" & lift > 0.9)
rules_izquierda_plf15_19R12<-subset(rules15_19, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_19E12)
summary(rules_izquierda_plf15_19G12)
summary(rules_izquierda_plf15_19R12)
inspect(rules_izquierda_plf15_19E12)
inspect(rules_izquierda_plf15_19G12)
inspect(rules_izquierda_plf15_19R12)

rules15_22<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9), appearance=list(lhs=c("X15LP_COMMUNICATION=Excellent","X15LP_COMMUNICATION=Good","X15LP_COMMUNICATION=Regular", "X22EM_RESULT_ASSES_ONTIME=Excellent", "X22EM_RESULT_ASSES_ONTIME=Good", "X22EM_RESULT_ASSES_ONTIME=Regular"), default="rhs"))
rules_izquierda_plf15_22E12<-subset(rules15_22, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent" & lift > 0.9)
rules_izquierda_plf15_22G12<-subset(rules15_22, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Good" & lift > 0.9)
rules_izquierda_plf15_22R12<-subset(rules15_22, subset= rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular" & lift > 0.9)
summary(rules_izquierda_plf15_22E12)
summary(rules_izquierda_plf15_22G12)
summary(rules_izquierda_plf15_22R12)
inspect(rules_izquierda_plf15_22E12)
inspect(rules_izquierda_plf15_22G12)
inspect(rules_izquierda_plf15_22R12)


##Impresion de todas las reglas
inspect(rules_izquierda_plf12_15E9)
inspect(rules_izquierda_plf12_15G9)
inspect(rules_izquierda_plf12_15R9)

inspect(rules_izquierda_plf12_19E9)
inspect(rules_izquierda_plf12_19G9)
inspect(rules_izquierda_plf12_19R9)

inspect(rules_izquierda_plf12_22E9)
inspect(rules_izquierda_plf12_22G9)
inspect(rules_izquierda_plf12_22R9)

inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf15_19R9)

inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf15_19R9)

inspect(rules_izquierda_plf19_22E9)
inspect(rules_izquierda_plf19_22G9)
inspect(rules_izquierda_plf19_22R9)

inspect(rules_izquierda_plf12_15E19)
inspect(rules_izquierda_plf12_15G19)
inspect(rules_izquierda_plf12_15R19)

inspect(rules_izquierda_plf12_22E19)
inspect(rules_izquierda_plf12_22G19)
inspect(rules_izquierda_plf12_22R19)

inspect(rules_izquierda_plf15_22E19)
inspect(rules_izquierda_plf15_22G19)
inspect(rules_izquierda_plf15_22R19)

inspect(rules_izquierda_plf12_15E14)
inspect(rules_izquierda_plf12_15G14)
inspect(rules_izquierda_plf12_15R14)

inspect(rules_izquierda_plf12_19E14)
inspect(rules_izquierda_plf12_19G14)
inspect(rules_izquierda_plf12_19R14)

inspect(rules_izquierda_plf12_22E14)
inspect(rules_izquierda_plf12_22G14)
inspect(rules_izquierda_plf12_22R14)

inspect(rules_izquierda_plf15_19E14)
inspect(rules_izquierda_plf15_19G14)
inspect(rules_izquierda_plf15_19R14)

inspect(rules_izquierda_plf19_22E14)
inspect(rules_izquierda_plf19_22G14)
inspect(rules_izquierda_plf19_22R14)

inspect(rules_izquierda_plf15_22E14)
inspect(rules_izquierda_plf15_22G14)
inspect(rules_izquierda_plf15_22R14)

inspect(rules_izquierda_plf12_15E21)
inspect(rules_izquierda_plf12_15G21)
inspect(rules_izquierda_plf12_15R21)

inspect(rules_izquierda_plf12_19E21)
inspect(rules_izquierda_plf12_19G21)
inspect(rules_izquierda_plf12_19R21)

inspect(rules_izquierda_plf12_15E6)
inspect(rules_izquierda_plf12_15G6)
inspect(rules_izquierda_plf12_15R6)

inspect(rules_izquierda_plf12_19E6)
inspect(rules_izquierda_plf12_19G6)
inspect(rules_izquierda_plf12_19R6)

inspect(rules_izquierda_plf12_22E6)
inspect(rules_izquierda_plf12_22G6)
inspect(rules_izquierda_plf12_22R6)

inspect(rules_izquierda_plf15_19E6)
inspect(rules_izquierda_plf15_19G6)
inspect(rules_izquierda_plf15_19R6)

inspect(rules_izquierda_plf15_22E6)
inspect(rules_izquierda_plf15_22G6)
inspect(rules_izquierda_plf15_22R6)

inspect(rules_izquierda_plf19_22E6)
inspect(rules_izquierda_plf19_22G6)
inspect(rules_izquierda_plf19_22R6)

inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf12_19R18)

inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf12_19R18)

inspect(rules_izquierda_plf15_19E18)
inspect(rules_izquierda_plf15_19G18)
inspect(rules_izquierda_plf15_19R18)

inspect(rules_izquierda_plf12_15E18)
inspect(rules_izquierda_plf12_15G18)
inspect(rules_izquierda_plf12_15R18)

inspect(rules_izquierda_plf15_22E18)
inspect(rules_izquierda_plf15_22G18)
inspect(rules_izquierda_plf15_22R18)

inspect(rules_izquierda_plf19_22E18)
inspect(rules_izquierda_plf19_22G18)
inspect(rules_izquierda_plf19_22R18)

inspect(rules_izquierda_plf12_22E21)
inspect(rules_izquierda_plf12_22G21)
inspect(rules_izquierda_plf12_22R21)

inspect(rules_izquierda_plf15_19E21)
inspect(rules_izquierda_plf15_19G21)
inspect(rules_izquierda_plf15_19R21)

inspect(rules_izquierda_plf19_22E21)
inspect(rules_izquierda_plf19_22G21)
inspect(rules_izquierda_plf19_22R21)

inspect(rules_izquierda_plf15_22E21)
inspect(rules_izquierda_plf15_22G21)
inspect(rules_izquierda_plf15_22R21)

inspect(rules_izquierda_plf15_19E12)
inspect(rules_izquierda_plf15_19G12)
inspect(rules_izquierda_plf15_19R12)

inspect(rules_izquierda_plf15_22E12)
inspect(rules_izquierda_plf15_22G12)
inspect(rules_izquierda_plf15_22R12)

#impresion de las reglas de las variables target & predictor


inspect(rules_izquierda_plf12_15E9)
inspect(rules_izquierda_plf12_19E9)
inspect(rules_izquierda_plf12_22E9)
inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf15_19E9)
inspect(rules_izquierda_plf19_22E9)
inspect(rules_izquierda_plf12_15E19)
inspect(rules_izquierda_plf12_22E19)
inspect(rules_izquierda_plf15_22E19)
inspect(rules_izquierda_plf12_15E14)
inspect(rules_izquierda_plf12_19E14)
inspect(rules_izquierda_plf12_22E14)
inspect(rules_izquierda_plf15_19E14)
inspect(rules_izquierda_plf19_22E14)
inspect(rules_izquierda_plf15_22E14)
inspect(rules_izquierda_plf12_15E21)
inspect(rules_izquierda_plf12_19E21)
inspect(rules_izquierda_plf12_15E6)
inspect(rules_izquierda_plf12_22E6)
inspect(rules_izquierda_plf15_19E6)
inspect(rules_izquierda_plf15_22E6)
inspect(rules_izquierda_plf19_22E6)
inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf12_19E18)
inspect(rules_izquierda_plf15_19E18)
inspect(rules_izquierda_plf12_15E18)
inspect(rules_izquierda_plf15_22E18)
inspect(rules_izquierda_plf19_22E18)
inspect(rules_izquierda_plf12_22E21)
inspect(rules_izquierda_plf15_19E21)
inspect(rules_izquierda_plf19_22E21)
inspect(rules_izquierda_plf15_22E21)
inspect(rules_izquierda_plf15_19E12)
inspect(rules_izquierda_plf15_22E12)

inspect(rules_izquierda_plf12_15G9)
inspect(rules_izquierda_plf12_19G9)
inspect(rules_izquierda_plf12_22G9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf15_19G9)
inspect(rules_izquierda_plf19_22G9)
inspect(rules_izquierda_plf12_15G19)
inspect(rules_izquierda_plf12_22G19)
inspect(rules_izquierda_plf15_22G19)
inspect(rules_izquierda_plf12_15G14)
inspect(rules_izquierda_plf12_19G14)
inspect(rules_izquierda_plf12_22G14)
inspect(rules_izquierda_plf15_19G14)
inspect(rules_izquierda_plf19_22G14)
inspect(rules_izquierda_plf15_22G14)
inspect(rules_izquierda_plf12_15G21)
inspect(rules_izquierda_plf12_19G21)
inspect(rules_izquierda_plf12_15G6)
inspect(rules_izquierda_plf12_19G6)
inspect(rules_izquierda_plf12_22G6)
inspect(rules_izquierda_plf15_19G6)
inspect(rules_izquierda_plf15_22G6)
inspect(rules_izquierda_plf19_22G6)
inspect(rules_izquierda_plf12_15G6)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf12_19G18)
inspect(rules_izquierda_plf15_19G18)
inspect(rules_izquierda_plf12_15G18)
inspect(rules_izquierda_plf15_22G18)
inspect(rules_izquierda_plf19_22G18)
inspect(rules_izquierda_plf12_22G21)
inspect(rules_izquierda_plf15_19G21)
inspect(rules_izquierda_plf19_22G21)
inspect(rules_izquierda_plf15_22G21)
inspect(rules_izquierda_plf15_19G12)
inspect(rules_izquierda_plf15_22G12)


inspect(rules_izquierda_plf12_15R9)
inspect(rules_izquierda_plf12_19R9)
inspect(rules_izquierda_plf12_22R9)
inspect(rules_izquierda_plf15_19R9)
inspect(rules_izquierda_plf15_19R9)
inspect(rules_izquierda_plf19_22R9)
inspect(rules_izquierda_plf12_15R19)
inspect(rules_izquierda_plf12_22R19)
inspect(rules_izquierda_plf15_22R19)
inspect(rules_izquierda_plf12_15R14)
inspect(rules_izquierda_plf12_19R14)
inspect(rules_izquierda_plf12_22R14)
inspect(rules_izquierda_plf15_19R14)
inspect(rules_izquierda_plf19_22R14)
inspect(rules_izquierda_plf15_22R14)
inspect(rules_izquierda_plf12_15R21)
inspect(rules_izquierda_plf12_19R21)
inspect(rules_izquierda_plf12_15R6)
inspect(rules_izquierda_plf12_19R6)
inspect(rules_izquierda_plf12_22R6)
inspect(rules_izquierda_plf15_19R6)
inspect(rules_izquierda_plf15_22R6)
inspect(rules_izquierda_plf19_22R6)
inspect(rules_izquierda_plf12_19R18)
inspect(rules_izquierda_plf15_19R18)
inspect(rules_izquierda_plf12_15R18)
inspect(rules_izquierda_plf15_22R18)
inspect(rules_izquierda_plf19_22R18)
inspect(rules_izquierda_plf12_22R21)
inspect(rules_izquierda_plf15_19R21)
inspect(rules_izquierda_plf19_22R21)
inspect(rules_izquierda_plf15_22R21)
inspect(rules_izquierda_plf15_19R12)
inspect(rules_izquierda_plf15_22R12)


##plot(rules, method="grouped", control=list(k=5))



rules_plfE1<-subset(rules, subset = rhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_plfE1)
rules_plfE2<-subset(rules, subset = rhs %in% "X2D_PRES_SCHED=Excellent" & lift > 0.9)
summary(rules_plfE2)

##voy eliminando de un grupo grande a un grupo chico y metiendo dentro de ese grupo 
##el resultado del grupo anterior.

rules_plfE3<-subset(rules, subset = rhs %in% "X3D_EVAL_PERIOD=Excellent" & lift > 0.9)
summary(rules_plfE3)
rules_izquierda_plfE3<-subset(rules_plfE3, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE3)
rules_izquierda2_plfE3<-subset(rules_izquierda_plfE3, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE3)
rules_izquierda3_plfE3<-subset(rules_izquierda2_plfE3, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE3)
rules_izquierda4_plfE3<-subset(rules_izquierda3_plfE3, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE3)
rules_izquierda5_plfE3<-subset(rules_izquierda4_plfE3, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE3)
rules_izquierda6_plfE3<-subset(rules_izquierda5_plfE3, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE3)
inspect(head(sort(rules_izquierda6_plfE3, by ="confidence"), n=42))


rules_plfE4<-subset(rules, subset = rhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_plfE4)
rules_plfE5<-subset(rules, subset = rhs %in% "X5D_INSTR_FOR_ASSESSMENTS=Excellent" & lift > 0.9)
summary(rules_plfE5)

rules_plfE6<-subset(rules, subset = rhs %in% "X6D_RESEARC_MOTIV=Excellent" & lift > 0.9)
summary(rules_plfE6)
rules_izquierda_plfE6<-subset(rules_plfE6, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE6)
rules_izquierda2_plfE6<-subset(rules_izquierda_plfE6, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE6)
rules_izquierda3_plfE6<-subset(rules_izquierda2_plfE6, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE6)
rules_izquierda4_plfE6<-subset(rules_izquierda3_plfE6, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE6)
rules_izquierda5_plfE6<-subset(rules_izquierda4_plfE6, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE6)
rules_izquierda6_plfE6<-subset(rules_izquierda5_plfE6, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE6)
inspect(head(sort(rules_izquierda6_plfE6, by ="confidence"), n=42))


rules_plfE7<-subset(rules, subset = rhs %in% "X7LP_PRE_INF_SCHED=Excellent" & lift > 0.9)
summary(rules_plfE7)
rules_plfE8<-subset(rules, subset = rhs %in% "X8LP_PRE_INF_POLICY_CLASS=Excellent" & lift > 0.9)
summary(rules_plfE8)

rules_plfE9<-subset(rules, subset = rhs %in% "X9LP_ENCOUR_PARTICIP=Excellent" & lift > 0.9)
summary(rules_plfE9)
rules_izquierda_plfE9<-subset(rules_plfE9, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE9)
rules_izquierda2_plfE9<-subset(rules_izquierda_plfE9, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE9)
rules_izquierda3_plfE9<-subset(rules_izquierda2_plfE9, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE9)
rules_izquierda4_plfE9<-subset(rules_izquierda3_plfE9, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE9)
rules_izquierda5_plfE9<-subset(rules_izquierda4_plfE9, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE9)
rules_izquierda6_plfE9<-subset(rules_izquierda5_plfE9, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE9)
inspect(head(sort(rules_izquierda6_plfE9, by ="confidence"), n=10))


rules_plfE10<-subset(rules, subset = rhs %in% "X10LP_SUMM_LAST_TOPICS=Excellent" & lift > 0.9)
summary(rules_plfE10)

##rules_plfE10<-subset(rules, subset = rhs %in% "X10LP_SUMM_LAST_TOPICS=Excellent", lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent")
##summary(rules_plfE10)



rules_plfE11<-subset(rules, subset = rhs %in% "X11LP_NEWCONCEP_USING_LAST_KNOWLED=Excellent" & lift > 0.9)
summary(rules_plfE11)

rules_plfE12<-subset(rules, subset = rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Excellent" & lift > 0.9)
summary(rules_plfE12)
rules_izquierda_plfE12<-subset(rules_plfE12, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE12)
rules_izquierda2_plfE12<-subset(rules_izquierda_plfE12, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE12)
rules_izquierda3_plfE12<-subset(rules_izquierda2_plfE12, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE12)
rules_izquierda4_plfE12<-subset(rules_izquierda3_plfE12, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE12)
rules_izquierda5_plfE12<-subset(rules_izquierda4_plfE12, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE12)
rules_izquierda6_plfE12<-subset(rules_izquierda5_plfE12, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE12)
inspect(head(sort(rules_izquierda6_plfE12, by ="confidence"), n=10))

rules_plfE13<-subset(rules, subset = rhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_plfE13)
rules_plfE14<-subset(rules, subset = rhs %in% "X14LP_REFLX_ON_TOPICS=Excellent" & lift > 0.9)
summary(rules_plfE14)
rules_plfE15<-subset(rules, subset = rhs %in% "X15LP_COMMUNICATION=Excellent" & lift > 0.9)
summary(rules_plfE15)
rules_plfE16<-subset(rules, subset = rhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_plfE16)
rules_plfE17<-subset(rules, subset = rhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_plfE17)
rules_plfE18<-subset(rules, subset = rhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_plfE18)

rules_plfE19<-subset(rules, subset = rhs %in% "X19LP_CONT_UNDERST=Excellent" & lift > 0.9)
summary(rules_plfE19)
rules_izquierda_plfE19<-subset(rules_plfE19, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE19)
rules_izquierda2_plfE19<-subset(rules_izquierda_plfE19, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE19)
rules_izquierda3_plfE19<-subset(rules_izquierda2_plfE19, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE19)
rules_izquierda4_plfE19<-subset(rules_izquierda3_plfE19, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE19)
rules_izquierda5_plfE19<-subset(rules_izquierda4_plfE19, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE19)
rules_izquierda6_plfE19<-subset(rules_izquierda5_plfE19, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE19)
inspect(head(sort(rules_izquierda6_plfE19, by ="confidence"), n=10))


rules_plfE20<-subset(rules, subset = rhs %in% "X20PT_PREPAR_RESOURCES=Excellent" & lift > 0.9)
summary(rules_plfE20)
rules_plfE21<-subset(rules, subset = rhs %in% "X21PT_USE_SCHEMES=Excellent" & lift > 0.9)
summary(rules_plfE21)

rules_plfE22<-subset(rules, subset = rhs %in% "X22EM_RESULT_ASSES_ONTIME=Excellent" & lift > 0.9)
summary(rules_plfE22)
rules_izquierda_plfE22<-subset(rules_plfE22, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE22)
rules_izquierda2_plfE22<-subset(rules_izquierda_plfE22, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE22)
rules_izquierda3_plfE22<-subset(rules_izquierda2_plfE22, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE22)
rules_izquierda4_plfE22<-subset(rules_izquierda3_plfE22, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE22)
rules_izquierda5_plfE22<-subset(rules_izquierda4_plfE22, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE22)
rules_izquierda6_plfE22<-subset(rules_izquierda5_plfE22, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE22)
inspect(head(sort(rules_izquierda6_plfE22, by ="confidence"), n=10))

rules_plfE23<-subset(rules, subset = rhs %in% "X23EM_ARRIVE_ONTIME=Excellent" & lift > 0.9)
summary(rules_plfE23)
rules_izquierda_plfE23<-subset(rules_plfE23, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Excellent" & lift > 0.9)
summary(rules_izquierda_plfE23)
rules_izquierda2_plfE23<-subset(rules_izquierda_plfE23, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda2_plfE23)
rules_izquierda3_plfE23<-subset(rules_izquierda2_plfE23, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Excellent" & lift > 0.9)
summary(rules_izquierda3_plfE23)
rules_izquierda4_plfE23<-subset(rules_izquierda3_plfE23, subset = lhs %in% "X16LP_RESPECTFUL=Excellent" & lift > 0.9)
summary(rules_izquierda4_plfE23)
rules_izquierda5_plfE23<-subset(rules_izquierda4_plfE23, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Excellent" & lift > 0.9)
summary(rules_izquierda5_plfE23)
rules_izquierda6_plfE23<-subset(rules_izquierda5_plfE23, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Excellent" & lift > 0.9)
summary(rules_izquierda6_plfE23)
inspect(head(sort(rules_izquierda6_plfE23, by ="confidence"), n=10))


inspect(head(sort(rules_plfE1, by ="confidence"), n=3))
inspect(head(sort(rules_plfE2, by ="confidence"), n=3))
inspect(head(sort(rules_plfE3, by ="confidence"), n=3))
inspect(head(sort(rules_plfE4, by ="confidence"), n=3))
inspect(head(sort(rules_plfE5, by ="confidence"), n=3))
inspect(head(sort(rules_plfE6, by ="confidence"), n=3))
inspect(head(sort(rules_plfE7, by ="confidence"), n=3))
inspect(head(sort(rules_plfE8, by ="confidence"), n=3))
inspect(head(sort(rules_plfE9, by ="confidence"), n=3))
inspect(head(sort(rules_plfE10, by ="confidence"), n=3))
inspect(head(sort(rules_plfE11, by ="confidence"), n=3))
inspect(head(sort(rules_plfE12, by ="confidence"), n=3))
inspect(head(sort(rules_plfE13, by ="confidence"), n=3))
inspect(head(sort(rules_plfE14, by ="confidence"), n=3))
inspect(head(sort(rules_plfE15, by ="confidence"), n=3))
inspect(head(sort(rules_plfE16, by ="confidence"), n=3))
inspect(head(sort(rules_plfE17, by ="confidence"), n=3))
inspect(head(sort(rules_plfE18, by ="confidence"), n=3))
inspect(head(sort(rules_plfE19, by ="confidence"), n=3))
inspect(head(sort(rules_plfE20, by ="confidence"), n=3))
inspect(head(sort(rules_plfE21, by ="confidence"), n=3))
inspect(head(sort(rules_plfE22, by ="confidence"), n=3))
inspect(head(sort(rules_plfE23, by ="confidence"), n=3))

##write.csv(rules_plfE2, file="rulesgce.csv")(esto no funciona)
##sink()
##unlink("excellentresultsgce.txt")
##sink("toda_data_profe_lf.txt", append=TRUE, split=TRUE)

# REGULAR
# all attributes.
# we need to see for regular evaluations so we use a specific support , somtimes lower
# plot this to see what is in the rhs
# make an inspection about what we found in the rhs 

rules2<-apriori(variable_final,parameter=list(support=0.01,confidence=0.9))
#plot(rules2, method="grouped", control=list(k=5))

rules_plfR1<-subset(rules2, subset = rhs %in% "X1D_AUDIOVISUAL_HELP=Regular" & lift > 0.4)
summary(rules_plfR1)
rules_plfR2<-subset(rules2, subset = rhs %in% "X2D_PRES_SCHED=Regular" & lift > 0.4)
summary(rules_plfR2)

rules_plfR3<-subset(rules2, subset = rhs %in% "X3D_EVAL_PERIOD=Regular" & lift > 0.4)
summary(rules_plfR3)
rules_izquierda_plfR3<-subset(rules_plfR3, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Regular" & lift > 0.9)
summary(rules_izquierda_plfR3)
rules_izquierda2_plfR3<-subset(rules_izquierda_plfR3, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda2_plfR3)
rules_izquierda3_plfR3<-subset(rules_izquierda2_plfR3, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Regular" & lift > 0.9)
summary(rules_izquierda3_plfR3)
rules_izquierda4_plfR3<-subset(rules_izquierda3_plfR3, subset = lhs %in% "X16LP_RESPECTFUL=Regular" & lift > 0.9)
summary(rules_izquierda4_plfR3)
rules_izquierda5_plfR3<-subset(rules_izquierda4_plfR3, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Regular" & lift > 0.9)
summary(rules_izquierda5_plfR3)
rules_izquierda6_plfR3<-subset(rules_izquierda5_plfR3, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.9)
summary(rules_izquierda6_plfR3)
inspect(head(sort(rules_izquierda6_plfR3, by ="confidence"), n=15))

rules_plfR4<-subset(rules2, subset = rhs %in% "X4D_EVAL_RELAT_TOPICS=Regular" & lift > 0.4)
summary(rules_plfR4)
rules_plfR5<-subset(rules2, subset = rhs %in% "X5D_INSTR_FOR_ASSESSMENTS=Regular" & lift > 0.4)
summary(rules_plfR5)

rules_plfR6<-subset(rules2, subset = rhs %in% "X6D_RESEARC_MOTIV=Regular" & lift > 0.4)
summary(rules_plfR6)


rules_plfR7<-subset(rules2, subset = rhs %in% "X7LP_PRE_INF_SCHED=Regular" & lift > 0.4)
summary(rules_plfR7)
rules_plfR8<-subset(rules2, subset = rhs %in% "X8LP_PRE_INF_POLICY_CLASS=Regular" & lift > 0.4)
summary(rules_plfR8)
rules_plfR9<-subset(rules2, subset = rhs %in% "X9LP_ENCOUR_PARTICIP=Regular" & lift > 0.4)
summary(rules_plfR9)
rules_plfR10<-subset(rules2, subset = rhs %in% "X10LP_SUMM_LAST_TOPICS=Regular" & lift > 0.4)
summary(rules_plfR10)
rules_plfR11<-subset(rules2, subset = rhs %in% "X11LP_NEWCONCEP_USING_LAST_KNOWLED=Regular" & lift > 0.4)
summary(rules_plfR11)
rules_plfR12<-subset(rules2, subset = rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Regular" & lift > 0.4)
summary(rules_plfR12)
rules_plfR13<-subset(rules2, subset = rhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Regular" & lift > 0.4)
summary(rules_plfR13)
rules_plfR14<-subset(rules2, subset = rhs %in% "X14LP_REFLX_ON_TOPICS=Regular" & lift > 0.4)
summary(rules_plfR14)
rules_plfR15<-subset(rules2, subset = rhs %in% "X15LP_COMMUNICATION=Regular" & lift > 0.4)
summary(rules_plfR15)
rules_plfR16<-subset(rules2, subset = rhs %in% "X16LP_RESPECTFUL=Regular" & lift > 0.4)
summary(rules_plfR16)
rules_plfR17<-subset(rules2, subset = rhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Regular" & lift > 0.4)
summary(rules_plfR17)
rules_plfR18<-subset(rules2, subset = rhs %in% "X18LP_CONTENT_ORGANIZ=Regular" & lift > 0.4)
summary(rules_plfR18)
rules_plfR19<-subset(rules2, subset = rhs %in% "X19LP_CONT_UNDERST=Regular" & lift > 0.4)
summary(rules_plfR19)
rules_plfR20<-subset(rules2, subset = rhs %in% "X20PT_PREPAR_RESOURCES=Regular" & lift > 0.4)
summary(rules_plfR20)
rules_plfR21<-subset(rules2, subset = rhs %in% "X21PT_USE_SCHEMES=Regular" & lift > 0.4)
summary(rules_plfR21)
rules_plfR22<-subset(rules2, subset = rhs %in% "X22EM_RESULT_ASSES_ONTIME=Regular" & lift > 0.4)
summary(rules_plfR22)
rules_plfR23<-subset(rules2, subset = rhs %in% "X23EM_ARRIVE_ONTIME=Regular" & lift > 0.4)
summary(rules_plfR23)

inspect(head(sort(rules_plfR1, by ="lift"), n=3))
inspect(head(sort(rules_plfR2, by ="lift"), n=3))
inspect(head(sort(rules_plfR3, by ="lift"), n=3))
inspect(head(sort(rules_plfR4, by ="lift"), n=3))
inspect(head(sort(rules_plfR5, by ="lift"), n=3))
inspect(head(sort(rules_plfR6, by ="lift"), n=3))
inspect(head(sort(rules_plfR7, by ="lift"), n=3))
inspect(head(sort(rules_plfR8, by ="lift"), n=3))
inspect(head(sort(rules_plfR9, by ="lift"), n=3))
inspect(head(sort(rules_plfR10, by ="lift"), n=3))
inspect(head(sort(rules_plfR11, by ="lift"), n=3))
inspect(head(sort(rules_plfR12, by ="lift"), n=3))
inspect(head(sort(rules_plfR13, by ="lift"), n=3))
inspect(head(sort(rules_plfR14, by ="lift"), n=3))
inspect(head(sort(rules_plfR15, by ="lift"), n=3))
inspect(head(sort(rules_plfR16, by ="lift"), n=3))
inspect(head(sort(rules_plfR17, by ="lift"), n=3))
inspect(head(sort(rules_plfR18, by ="lift"), n=3))
inspect(head(sort(rules_plfR19, by ="lift"), n=3))
inspect(head(sort(rules_plfR20, by ="lift"), n=3))
inspect(head(sort(rules_plfR21, by ="lift"), n=3))
inspect(head(sort(rules_plfR22, by ="lift"), n=3))
inspect(head(sort(rules_plfR23, by ="lift"), n=3))


rules3<-apriori(variable_final,parameter=list(support=0.1,confidence=0.9))
#plot(rules2, method="grouped", control=list(k=5))

rules_plfG1<-subset(rules3, subset = rhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_plfG1)
rules_plfG2<-subset(rules3, subset = rhs %in% "X2D_PRES_SCHED=Good" & lift > 0.9)
summary(rules_plfG2)

rules_plfG3<-subset(rules3, subset = rhs %in% "X3D_EVAL_PERIOD=Good" & lift > 0.9)
summary(rules_plfG3)
rules_izquierda_plfG3<-subset(rules_plfG3, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG3)
rules_izquierda2_plfG3<-subset(rules_izquierda_plfG3, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG3)
rules_izquierda3_plfG3<-subset(rules_izquierda2_plfG3, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG3)
rules_izquierda4_plfG3<-subset(rules_izquierda3_plfG3, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG3)
rules_izquierda5_plfG3<-subset(rules_izquierda4_plfG3, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG3)
rules_izquierda6_plfG3<-subset(rules_izquierda5_plfG3, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG3)
inspect(head(sort(rules_izquierda6_plfG3, by ="confidence"), n=15))


rules_plfG4<-subset(rules3, subset = rhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_plfG4)
rules_plfG5<-subset(rules3, subset = rhs %in% "X5D_INSTR_FOR_ASSESSMENTS=Good" & lift > 0.9)
summary(rules_plfG5)

rules_plfG6<-subset(rules3, subset = rhs %in% "X6D_RESEARC_MOTIV=Good" & lift > 0.9)
summary(rules_plfG6)
rules_izquierda_plfG6<-subset(rules_plfG6, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG6)
rules_izquierda2_plfG6<-subset(rules_izquierda_plfG6, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG6)
rules_izquierda3_plfG6<-subset(rules_izquierda2_plfG6, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG6)
rules_izquierda4_plfG6<-subset(rules_izquierda3_plfG6, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG6)
rules_izquierda5_plfG6<-subset(rules_izquierda4_plfG6, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG6)
rules_izquierda6_plfG6<-subset(rules_izquierda5_plfG6, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG6)
inspect(head(sort(rules_izquierda6_plfG6, by ="confidence"), n=15))


summary(rules_plfG6)
rules_plfG7<-subset(rules3, subset = rhs %in% "X7LP_PRE_INF_SCHED=Good" & lift > 0.9)
summary(rules_plfG7)
rules_plfG8<-subset(rules3, subset = rhs %in% "X8LP_PRE_INF_POLICY_CLASS=Good" & lift > 0.9)
summary(rules_plfG8)

rules_plfG9<-subset(rules3, subset = rhs %in% "X9LP_ENCOUR_PARTICIP=Good" & lift > 0.9)
summary(rules_plfG9)
rules_izquierda_plfG9<-subset(rules_plfG9, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG9)
rules_izquierda2_plfG9<-subset(rules_izquierda_plfG9, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG9)
rules_izquierda3_plfG9<-subset(rules_izquierda2_plfG9, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG9)
rules_izquierda4_plfG9<-subset(rules_izquierda3_plfG9, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG9)
rules_izquierda5_plfG9<-subset(rules_izquierda4_plfG9, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG9)
rules_izquierda6_plfG9<-subset(rules_izquierda5_plfG9, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG9)
inspect(head(sort(rules_izquierda6_plfG9, by ="confidence"), n=15))


rules_plfG10<-subset(rules3, subset = rhs %in% "X10LP_SUMM_LAST_TOPICS=Good" & lift > 0.9)
summary(rules_plfG10)
rules_plfG11<-subset(rules3, subset = rhs %in% "X11LP_NEWCONCEP_USING_LAST_KNOWLED=Good" & lift > 0.9)
summary(rules_plfG11)

rules_plfG12<-subset(rules3, subset = rhs %in% "X12LP_MOTIV_LEARN_COURS_MATERIAL=Good" & lift > 0.9)
summary(rules_plfG12)
rules_izquierda_plfG12<-subset(rules_plfG12, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG12)
rules_izquierda2_plfG12<-subset(rules_izquierda_plfG12, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG12)
rules_izquierda3_plfG12<-subset(rules_izquierda2_plfG12, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG12)
rules_izquierda4_plfG12<-subset(rules_izquierda3_plfG12, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG12)
rules_izquierda5_plfG12<-subset(rules_izquierda4_plfG12, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG12)
rules_izquierda6_plfG12<-subset(rules_izquierda5_plfG12, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG12)
inspect(head(sort(rules_izquierda6_plfG12, by ="confidence"), n=15))


rules_plfG13<-subset(rules3, subset = rhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_plfG13)
rules_plfG14<-subset(rules3, subset = rhs %in% "X14LP_REFLX_ON_TOPICS=Good" & lift > 0.9)
summary(rules_plfG14)
rules_plfG15<-subset(rules3, subset = rhs %in% "X15LP_COMMUNICATION=Good" & lift > 0.9)
summary(rules_plfG15)
rules_plfG16<-subset(rules3, subset = rhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_plfG16)
rules_plfG17<-subset(rules3, subset = rhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_plfG17)
rules_plfG18<-subset(rules3, subset = rhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_plfG18)

rules_plfG19<-subset(rules3, subset = rhs %in% "X19LP_CONT_UNDERST=Good" & lift > 0.9)
summary(rules_plfG19)
rules_izquierda_plfG19<-subset(rules_plfG19, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG19)
rules_izquierda2_plfG19<-subset(rules_izquierda_plfG19, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG19)
rules_izquierda3_plfG19<-subset(rules_izquierda2_plfG19, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG19)
rules_izquierda4_plfG19<-subset(rules_izquierda3_plfG19, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG19)
rules_izquierda5_plfG19<-subset(rules_izquierda4_plfG19, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG19)
rules_izquierda6_plfG19<-subset(rules_izquierda5_plfG19, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG19)
inspect(head(sort(rules_izquierda6_plfG19, by ="confidence"), n=15))

rules_plfG20<-subset(rules3, subset = rhs %in% "X20PT_PREPAR_RESOURCES=Good" & lift > 0.9)
summary(rules_plfG20)
rules_plfG21<-subset(rules3, subset = rhs %in% "X21PT_USE_SCHEMES=Good" & lift > 0.9)
summary(rules_plfG21)

rules_plfG22<-subset(rules3, subset = rhs %in% "X22EM_RESULT_ASSES_ONTIME=Good" & lift > 0.9)
summary(rules_plfG22)
rules_izquierda_plfG22<-subset(rules_plfG22, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG22)
rules_izquierda2_plfG22<-subset(rules_izquierda_plfG22, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG22)
rules_izquierda3_plfG22<-subset(rules_izquierda2_plfG22, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG22)
rules_izquierda4_plfG22<-subset(rules_izquierda3_plfG22, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG22)
rules_izquierda5_plfG22<-subset(rules_izquierda4_plfG22, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG22)
rules_izquierda6_plfG22<-subset(rules_izquierda5_plfG22, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG22)
inspect(head(sort(rules_izquierda6_plfG22, by ="confidence"), n=15))

rules_plfG23<-subset(rules3, subset = rhs %in% "X23EM_ARRIVE_ONTIME=Good" & lift > 0.9)
summary(rules_plfG23)
rules_izquierda_plfG23<-subset(rules_plfG23, subset= lhs %in% "X1D_AUDIOVISUAL_HELP=Good" & lift > 0.9)
summary(rules_izquierda_plfG23)
rules_izquierda2_plfG23<-subset(rules_izquierda_plfG23, subset=lhs %in% "X4D_EVAL_RELAT_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda2_plfG23)
rules_izquierda3_plfG23<-subset(rules_izquierda2_plfG23, subset = lhs %in% "X13LP_ANSW_QUEST_OUTS_CLASS=Good" & lift > 0.9)
summary(rules_izquierda3_plfG23)
rules_izquierda4_plfG23<-subset(rules_izquierda3_plfG23, subset = lhs %in% "X16LP_RESPECTFUL=Good" & lift > 0.9)
summary(rules_izquierda4_plfG23)
rules_izquierda5_plfG23<-subset(rules_izquierda4_plfG23, subset = lhs %in% "X17LP_ANSW_QUEST_OF_TOPICS=Good" & lift > 0.9)
summary(rules_izquierda5_plfG23)
rules_izquierda6_plfG23<-subset(rules_izquierda5_plfG23, subset = lhs %in% "X18LP_CONTENT_ORGANIZ=Good" & lift > 0.9)
summary(rules_izquierda6_plfG23)
inspect(head(sort(rules_izquierda6_plfG23, by ="confidence"), n=15))


inspect(head(sort(rules_plfG1, by ="lift"), n=3))
inspect(head(sort(rules_plfG2, by ="lift"), n=3))
inspect(head(sort(rules_plfG3, by ="lift"), n=3))
inspect(head(sort(rules_plfG4, by ="lift"), n=3))
inspect(head(sort(rules_plfG5, by ="lift"), n=3))
inspect(head(sort(rules_plfG6, by ="lift"), n=3))
inspect(head(sort(rules_plfG7, by ="lift"), n=3))
inspect(head(sort(rules_plfG8, by ="lift"), n=3))
inspect(head(sort(rules_plfG9, by ="lift"), n=3))
inspect(head(sort(rules_plfG10, by ="lift"), n=3))
inspect(head(sort(rules_plfG11, by ="lift"), n=3))
inspect(head(sort(rules_plfG12, by ="lift"), n=3))
inspect(head(sort(rules_plfG13, by ="lift"), n=3))
inspect(head(sort(rules_plfG14, by ="lift"), n=3))
inspect(head(sort(rules_plfG15, by ="lift"), n=3))
inspect(head(sort(rules_plfG16, by ="lift"), n=3))
inspect(head(sort(rules_plfG17, by ="lift"), n=3))
inspect(head(sort(rules_plfG18, by ="lift"), n=3))
inspect(head(sort(rules_plfG19, by ="lift"), n=3))
inspect(head(sort(rules_plfG20, by ="lift"), n=3))
inspect(head(sort(rules_plfG21, by ="lift"), n=3))
inspect(head(sort(rules_plfG22, by ="lift"), n=3))
inspect(head(sort(rules_plfG23, by ="lift"), n=3))

sink("meta_know_proyectos_lfrg.txt", append=TRUE, split=TRUE)

#saveAsGraph(head(sort(rules, by="lift"),12), file="p8iche.graphml")

#saveAsGraph(head(sort(rules2, by="lift"),9), file="p8icheR.graphml")

#saveAsGraph(head(sort(rules, by="lift"),100), file="p8icheC.graphml")

#saveAsGraph(head(sort(rules2, by="lift"),100), file="p8icheRC.graphml")


